#!/usr/bin/env python3
"""Generate publication figures for the action-ripples paper.

Figures produced:
  fig2_surface.png   - magnitude/signature dissociation across OvS surfaces
  fig5_temporal.png  - raw change_volume_sum signal post-action for a flush rep
  fig6_features.png  - per-iteration feature distributions, ripple vs baseline

fig_crossdomain.png is produced by gen_crossdomain.py.
diag_metaphor.pdf is a hand-drawn diagram, not generated by code.

No classifier or anomaly score is used anywhere in this file. The event
indicator is a raw threshold: change_volume_sum > max(pre-action signal)
per rep. The data CSVs are produced by scripts/regen_figs_data.py.
"""
import json
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pathlib import Path

OUT = Path(__file__).parent
DATA = OUT / "data" / "processed"

plt.rcParams.update({
    "font.family": "serif",
    "font.size": 15,
    "axes.labelsize": 16,
    "axes.titlesize": 17,
    "xtick.labelsize": 14,
    "ytick.labelsize": 14,
    "legend.fontsize": 14,
    "figure.dpi": 100,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
    "axes.grid": True,
    "grid.alpha": 0.3,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "lines.linewidth": 2.0,
    "lines.markersize": 9,
})

PALETTE = {
    "anchored":   "#1b7837",
    "reactive":   "#7fbf7b",
    "induced":    "#762a83",
    "periodic":   "#fdb863",
    "endogenous": "#b35806",
    "neutral":    "#2c7bb6",
    "baseline":   "#a6cee3",
}


def fig2_surface():
    """Two panels showing the magnitude/signature dissociation at N=10.

    Panel A: per-rep ripple-event count per hour scattered against
    action surface; means roughly comparable across 1/21/200 entries
    with very high per-rep variance. The magnitude does not follow
    surface.

    Panel B: within-scenario pairwise cosine similarity of the
    post-action signal across reps. The signature reproducibility
    grows monotonically with surface.
    """
    df = pd.read_csv(DATA / "fig2_sparse_attack_cascade_per_rep.csv")
    sig = json.loads((DATA / "signature_summary.json").read_text())
    order = ["E_attack_single_rule", "F_attack_burst", "D_attack_flush"]
    labels = ["1\n(single-rule)", "21\n(burst)", "200\n(flush)"]
    means = np.array([df.loc[df["scenario"] == s, "per_hour_rate"].mean()
                      for s in order])
    stds = np.array([df.loc[df["scenario"] == s, "per_hour_rate"].std(ddof=1)
                     for s in order])
    raw = [df.loc[df["scenario"] == s, "per_hour_rate"].to_numpy() for s in order]
    sig_key = {"E_attack_single_rule": "OvS-Single",
               "F_attack_burst": "OvS-Burst",
               "D_attack_flush": "OvS-Flush"}
    within_mean = np.array([sig["per_scenario_within"][sig_key[s]]["within_mean"]
                            for s in order])
    within_std = np.array([sig["per_scenario_within"][sig_key[s]]["within_std"]
                           for s in order])
    # 95% rep-level bootstrap CIs reported in the body (Section results); used as
    # the panel-(b) whiskers so the figure and the text describe the same interval
    # (a raw +/-std would exceed the cosine maximum of 1.0 for the high-variance burst).
    within_ci = {"OvS-Single": (0.79, 0.91), "OvS-Burst": (0.32, 0.85),
                 "OvS-Flush": (0.93, 0.97)}
    ci = np.array([within_ci[sig_key[s]] for s in order])
    within_err = np.vstack([within_mean - ci[:, 0], ci[:, 1] - within_mean])

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5.5))
    x = np.arange(len(order))

    for i, vals in enumerate(raw):
        ax1.scatter(np.full_like(vals, i, dtype=float)
                    + np.random.RandomState(42 + i).uniform(-0.08, 0.08, len(vals)),
                    vals, s=45, color=PALETTE["induced"], alpha=0.55,
                    edgecolor="black", linewidth=0.5, zorder=2)
    ax1.errorbar(x, means, yerr=stds, fmt="s", markersize=11,
                 color="black", capsize=8, capthick=1.5,
                 linewidth=2, ecolor="black", zorder=3,
                 label="mean $\\pm$ std")
    # Position numeric labels well above the error bars in clear space,
    # centered horizontally over each category.
    y_top_a = max(max(r.max() for r in raw) * 1.18, 2500)
    for i, (m, s) in enumerate(zip(means, stds)):
        y_label = m + s + y_top_a * 0.04
        ax1.annotate(f"{m:.0f}", xy=(i, y_label), ha="center", va="bottom",
                     fontsize=12, fontweight="bold")
    ax1.set_xticks(x)
    ax1.set_xticklabels(labels)
    ax1.set_xlabel("Action surface (flow-table entries touched)")
    ax1.set_ylabel("Ripple events per hour")
    ax1.set_ylim(0, y_top_a)
    ax1.legend(loc="lower right")
    ax1.text(0.02, 0.97, "(a)", transform=ax1.transAxes,
             fontsize=18, fontweight="bold", va="top", ha="left")

    ax2.bar(x, within_mean, yerr=within_err, capsize=8,
            color=PALETTE["anchored"], edgecolor="black", linewidth=0.6,
            error_kw={"elinewidth": 1.5, "ecolor": "black"})
    # Place value labels above the error-bar caps in clear space.
    for i, (m, hi) in enumerate(zip(within_mean, ci[:, 1])):
        y_label = min(hi + 0.06, 1.22)
        ax2.annotate(f"{m:.2f}", xy=(i, y_label), ha="center", va="bottom",
                     fontsize=12, fontweight="bold")
    ax2.set_xticks(x)
    ax2.set_xticklabels(labels)
    ax2.set_xlabel("Action surface (flow-table entries touched)")
    ax2.set_ylabel("Within-scenario signature similarity\n(mean pairwise cosine)")
    ax2.set_ylim(0, 1.30)
    ax2.set_yticks([0.0, 0.2, 0.4, 0.6, 0.8, 1.0])
    ax2.axhline(sig["across_mean"], linestyle="--", color="gray",
                lw=1.0, alpha=0.7,
                label=f"across-scenario mean ({sig['across_mean']:.2f})")
    ax2.legend(loc="lower right", framealpha=0.95)
    ax2.text(0.02, 0.97, "(b)", transform=ax2.transAxes,
             fontsize=18, fontweight="bold", va="top", ha="left")

    plt.tight_layout()
    plt.savefig(OUT / "fig2_surface.png")
    plt.close()
    print(f"fig2 done (magnitude: {means.tolist()}, signature: {within_mean.tolist()})")


def fig5_temporal():
    """Excess-over-threshold per 5\\,s bucket, for a representative flush
    rep. For each 0.5\\,s iteration whose change\\_volume\\_sum signal
    exceeds the per-rep pre-action threshold, the excess (signal minus
    threshold, in bytes) is accumulated into the matching 5\\,s bucket;
    iterations below threshold contribute zero. Pre-action excess is
    small (rare narrow excursions just above the 95th percentile of the
    warmup); post-action excess is sustained and large, giving the
    temporal shape of the ripple cascade.
    """
    df = pd.read_csv(DATA / "fig5_temporal_signal.csv")
    df = df.sort_values("t_rel_s").reset_index(drop=True)
    t = df["t_rel_s"].values
    signal = df["signal"].values
    threshold = float(df["threshold"].iloc[0])
    excess = np.where(signal > threshold, signal - threshold, 0.0)

    action_t = 0.0
    bucket_s = 5.0
    edges = np.arange(-30.0, 200.0 + bucket_s, bucket_s)
    bidx = np.digitize(t, edges) - 1
    excess_sum = np.zeros(len(edges) - 1, dtype=float)
    for i, e in zip(bidx, excess):
        if 0 <= i < len(excess_sum):
            excess_sum[i] += float(e)
    centers = edges[:-1] + bucket_s / 2

    # Display in kB for readability.
    excess_kb = excess_sum / 1000.0

    fig, ax = plt.subplots(figsize=(12, 5))
    pre_mask = centers < 0
    post_mask = centers >= 0
    # Pre-action bars are deemphasized: light grey with low alpha. By
    # construction (95th-percentile threshold) ~5% of warmup iterations
    # sit just above the threshold, so a small residual is expected;
    # this is the noise floor against which the post-action cascade is
    # compared, not a signal.
    ax.bar(centers[pre_mask], excess_kb[pre_mask], width=bucket_s * 0.9,
           color="#bbbbbb", edgecolor="#888888", linewidth=0.3, alpha=0.6,
           label="Pre-action residual (noise floor)")
    ax.bar(centers[post_mask], excess_kb[post_mask], width=bucket_s * 0.9,
           color=PALETTE["induced"], edgecolor="black", linewidth=0.5,
           label="Post-action ripple")
    ax.axvline(action_t, color="red", linewidth=2.5, label="Action injected")
    ax.set_xlabel("Time relative to action (s)")
    ax.set_ylabel("Excess kB / 5 s bucket")
    ax.set_title("Temporal Profile of a Ripple Cascade (Flow-table Flush)")
    xmax_data = float(t[t < 200].max()) if (t < 200).any() else 170.0
    xmax = int(np.ceil(xmax_data / 10.0) * 10) + 5
    ax.set_xlim(-30, xmax)
    ax.set_ylim(0, max(excess_kb.max() * 1.2, 0.3))
    ax.legend(loc="upper right", framealpha=0.95)
    pre_total_b = excess_sum[pre_mask].sum()
    post_total_b = excess_sum[post_mask].sum()
    ratio_pp = (post_total_b / pre_total_b) if pre_total_b > 0 else float("inf")
    txt = (f"threshold = {threshold:.0f} B (95th pct of warmup change_volume_sum);\n"
           f"bars sum (signal - threshold) over iterations above threshold\n"
           f"pre-action total: {pre_total_b:.0f} B    "
           f"post-action total: {post_total_b:.0f} B    "
           f"ratio: {ratio_pp:.1f}x")
    ax.text(0.01, 0.97, txt, transform=ax.transAxes, ha="left", va="top",
            fontsize=9, style="italic",
            bbox=dict(boxstyle="round,pad=0.3", facecolor="white",
                      edgecolor="grey", alpha=0.9))
    plt.tight_layout()
    plt.savefig(OUT / "fig5_temporal.png", bbox_inches="tight")
    plt.close()
    pre_total = excess_sum[pre_mask].sum()
    post_total = excess_sum[post_mask].sum()
    ratio = (post_total / pre_total) if pre_total > 0 else float("inf")
    print(f"fig5 done (threshold={threshold:.0f}, pre-action excess sum={pre_total:.0f} B, "
          f"post-action excess sum={post_total:.0f} B, ratio={ratio:.1f}x)")


def fig6_features():
    """Per-iteration feature signature: ripple iterations vs baseline iterations.

    Ripple iteration = post-action iteration whose change_volume_sum exceeds
    the pre-action maximum of the same rep.
    Baseline iteration = pre-action period of the same rep + three idle reps.
    """
    features = ["Active pages", "Volume sum\n($\\times 10^3$ B)",
                "High-region\npages", "Entropy\n(changed bytes)"]
    csv_labels = ["Active pages", "Volume sum",
                  "High-region pages", "Entropy (changed)"]
    scales = np.array([1.0, 1e-3, 1.0, 1.0])

    df = pd.read_csv(DATA / "fig6_feature_distributions.csv")
    normal = np.zeros(len(features))
    normal_std = np.zeros(len(features))
    ripple = np.zeros(len(features))
    ripple_std = np.zeros(len(features))
    for i, lab in enumerate(csv_labels):
        b = df[(df["feature"] == lab) & (df["kind"] == "baseline")]["value"].values
        r = df[(df["feature"] == lab) & (df["kind"] == "ripple")]["value"].values
        normal[i] = b.mean() * scales[i]
        normal_std[i] = b.std(ddof=1) * scales[i]
        ripple[i] = r.mean() * scales[i]
        ripple_std[i] = r.std(ddof=1) * scales[i]

    fig, ax = plt.subplots(figsize=(10.5, 5.5))
    x = np.arange(len(features))
    width = 0.36
    bars1 = ax.bar(x - width/2, normal, width, yerr=normal_std,
                    capsize=4, label="Baseline iteration",
                    color=PALETTE["baseline"], edgecolor="black", linewidth=0.5,
                    error_kw={"elinewidth": 1, "ecolor": "black"})
    bars2 = ax.bar(x + width/2, ripple, width, yerr=ripple_std,
                    capsize=4, label="Ripple iteration",
                    color=PALETTE["induced"], edgecolor="black", linewidth=0.5,
                    error_kw={"elinewidth": 1, "ecolor": "black"})
    ax.set_xticks(x)
    ax.set_xticklabels(features, fontsize=11)
    ax.set_ylabel("Mean feature value")
    ax.set_title("Feature Signature: Ripple vs Baseline Iterations", pad=12)
    ax.legend(loc="upper left", framealpha=0.95)
    # Headroom above tallest error-bar top so labels never collide
    top_baseline = (normal + normal_std).max()
    top_ripple = (ripple + ripple_std).max()
    y_max = max(top_baseline, top_ripple) * 1.18
    ax.set_ylim(top=y_max)
    offset = y_max * 0.02
    for bar, v, s in zip(bars1, normal, normal_std):
        ax.text(bar.get_x()+bar.get_width()/2, v + s + offset, f"{v:.1f}",
                ha="center", va="bottom", fontsize=10)
    for bar, v, s in zip(bars2, ripple, ripple_std):
        ax.text(bar.get_x()+bar.get_width()/2, v + s + offset, f"{v:.1f}",
                ha="center", va="bottom", fontsize=10)
    plt.tight_layout()
    plt.savefig(OUT / "fig6_features.png")
    plt.close()
    print(f"fig6 done (baseline={normal.tolist()}, ripple={ripple.tolist()})")


if __name__ == "__main__":
    fig2_surface()
    fig5_temporal()
    fig6_features()
    print("\nFigures regenerated (excluding fig_crossdomain — generated by gen_crossdomain.py).")
